version: '3.9'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: ms-sql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes: 
      - data:/var/opt/mssql/data/
  rfe-auth-api:
    build: .
    environment: 
      SQLServer: "ms-sql-server"
    container_name: rfe-auth-api
    ports: 
      - "8080:80" 
volumes:
  data: 