version: '3.9'
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongPassword123!
      POSTGRES_DB: rfe-auth
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rfe-auth" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rfe-auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rfe-auth-api
    ports:
      - "80:8080"
  rfe-auth-web:
    build:
      context: ./rfe.auth.web
      dockerfile: Dockerfile
    container_name: rfe-auth-web
    ports:
      - "3001:80"
    depends_on:
      - rfe-auth-api
volumes:
  auth_data:
    # Backup Data # docker run --rm --volumes-from ms-sql-server -v ${PWD}/data:/backup busybox tar cvfz /backup/sqldata.tar var/opt/mssql/data/  
    # Restore Backup # docker run --rm --volumes-from ms-sql-server -v ${PWD}/data:/backup busybox tar xvf /backup/sqldata.tar 
    # docker run -v rfeauthnetcore_data:/var/opt/mssql/data/ -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Pa55w0rd2021' -e 'MSSQL_PID=Express' -p 1433:1433 -d --name ms-sql-server  mcr.microsoft.com/mssql/server:2017-latest-ubuntu

networks:
  default:
    name: rfe-network
    external: true


