name: Deploy on AWS
on: 
  push:
    branches:
      - deploy
jobs:
  deploy-on-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2
        
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 3.1.21
      - name: Build With Dotnet
        run: dotnet build -c release -o deploy
        
      - name: Generate Deployment Package  
        run: zip -r deploy.zip ./deploy/* 
         
      - name: Get timestamp
        uses: gerred/actions/current-time@v2
        id: current-time
        
      - name: Run string replace
        uses : frabert/replace-string-action@v2
        id: format-time
        with: 
          pattern: '[:\.]'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
          
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRETE_ACCESS_KEY }}
          application_name: rfe.netcore.auth
          environment_name: Rfenetcoreauth-env
          version_label: "rfe.netcore.auth-${{ steps.format-time.outputs.replaced }}"
          region: ap-south-1
          deployment_package: deploy.zip
      

  
